---
apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  selector:
    app: todo
  type: LoadBalancer
  ports:
  - name: todo
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: todo
  labels:
    app: todo
spec:
  containers:
  - name: todo
    image: htrvolker/todo-app:sqlite
    env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: credentials
          key: secret-key
